##Ejercicio SQL##
Se cuenta con cinco tablas Libro, LibAut, Prestamo, Autor, Estudiante.
![image.png]()

El ejercicio se realiza en Colab simulando el entorno de SQL

In [1]:
# Importación de la librería sqlite3 e iniciación de la conexión
import sqlite3
conn = sqlite3.connect(":memory:")
cur = conn.cursor()

In [ ]:
conn.executescript(
    """
    DROP TABLE Libro;
    DROP TABLE Autor;
    DROP TABLE Estudiante;
    DROP TABLE LibAut;
    DROP TABLE Prestamo;
    """
)

In [44]:
conn.executescript(
    """
    DROP TABLE Autor;
    """
)

In [13]:
# Creación de la tabla libro
conn.executescript(
    """
CREATE TABLE Libro (
Id_Libro INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
Titulo VARCHAR(100) NOT NULL,
Editorial VARCHAR(100) NOT NULL,
Area VARCHAR(100) NOT NULL
);

INSERT INTO Libro VALUES (1,'El Señor de las Moscas','Marruecos','Novela');
INSERT INTO Libro VALUES (2,'El Esclavo','Porrua','Narracion');
INSERT INTO Libro VALUES (3,'El Señor de los Anillos','FCE','Internet');
INSERT INTO Libro VALUES (4,'Don Quijote de la Mancha','Grijalva','Narracion');
INSERT INTO Libro VALUES (5,'visual Estudio Net','Alfay Omega','informatica');
INSERT INTO Libro VALUES (6,'Base de Datos','Alfay Omega','informatica');
INSERT INTO Libro VALUES (7,'Ingenieria de Software','Alfay Omega','informatica');
INSERT INTO Libro VALUES (8,'Un Mexicano Mas','planeta','novela');
INSERT INTO Libro VALUES (9,'Entregame tu corazon','Marruecos','Novela');
INSERT INTO Libro VALUES (10,'Harry Potter','edicciones prado','Internet');
INSERT INTO Libro VALUES (11,'Harry Potter:Las Reliquias de la Muerte ','edicciones prado','Internet');
INSERT INTO Libro VALUES (12,'Orgullo y Prejuicio','Marruecos','Novela');
INSERT INTO Libro VALUES (13,'Romeo y Julienta','Marruecos','Novela');
INSERT INTO Libro VALUES (14,'Navidad en las Montañas','Marruecos','Narracion');
INSERT INTO Libro VALUES (15,'El Señor de los Anillos: Las Dos Torres','FCE','Internet');
INSERT INTO Libro VALUES (16,'Emma','Marruecos','Novela');
INSERT INTO Libro VALUES (17,'Sensatez y sensibilidad','Marruecos','Novela');
INSERT INTO Libro VALUES (18,'La Muerte','Marruecos','Novela');
INSERT INTO Libro VALUES (19,'La Tregua','Marruecos','Novela');
    """
)
conn.commit()

In [45]:
# Creación de la tabla Autor
conn.executescript(
    """
CREATE TABLE Autor
(
Id_Autor INT PRIMARY KEY,
Nombre VARCHAR(100),
Nacionalidad VARCHAR(100)
); 

INSERT INTO Autor VALUES (16,'Juan Rufol','mexicano');
INSERT INTO Autor VALUES (17,'Willian Golding','Alemania');
INSERT INTO Autor VALUES (18,'Barbara Gostmich','Francia');
INSERT INTO Autor VALUES (19,'Mario Benedetti','USA');
INSERT INTO Autor VALUES (20,'Altamirano','mexicano');
INSERT INTO Autor VALUES (21,'Jose Gonzalez','italiano');
INSERT INTO Autor VALUES (22,'Ana laura Delgado','mexicano');
INSERT INTO Autor VALUES (23,'Og Mandino','USA');
INSERT INTO Autor VALUES (24,'thomas Huxley','japones');
INSERT INTO Autor VALUES (25,'Leticia Lopez Juarez','Canadiense');
INSERT INTO Autor VALUES (26,'Osar Palacios Ceballos','mexicano');
INSERT INTO Autor VALUES (27,'Zamná Heredia','portugues');
INSERT INTO Autor VALUES (28,'maria Bernaldez ','mexicano');
INSERT INTO Autor VALUES (29,'Jhon y Rita Lang','italiano');
INSERT INTO Autor VALUES (30,'Rafael Camacho','chileno');
INSERT INTO Autor VALUES (31,'Jane Austen','Inglesa');
    """
)
conn.commit()

In [38]:
# Creación de la tabla Estudiante
conn.executescript(
    """
CREATE TABLE Estudiante
(
Id_Lector INT PRIMARY KEY,
CI VARCHAR(9),
Nombre VARCHAR(100),
Apellido VARCHAR(100),
Direccion VARCHAR(100),
Carrera VARCHAR(100),
Edad VARCHAR(9)
); 

INSERT INTO Estudiante VALUES  (31,'3498','Maria','Lopez','noche triste','contabilidad','17');
INSERT INTO Estudiante VALUES  (32,'3498','Jonathan','Garcia','morelos no 7','alimentos','17');
INSERT INTO Estudiante VALUES  (33,'6295','roberto','Duque','flor de azalia SN','agrobiotecnologia','20');
INSERT INTO Estudiante VALUES  (34,'3452','Paola','Zapata','Av. Zaragoza','contabilidad','18');
INSERT INTO Estudiante VALUES  (35,'3792','mayra','Aguirre','Allende No 3','alimentos','22');
INSERT INTO Estudiante VALUES  (36,'6295','ivan','Solis','Galeana No23','contabilidad','19');
INSERT INTO Estudiante VALUES (37,'2443','Alexander','zuluaga','Guerrero No8','contabilidad','18');
INSERT INTO Estudiante VALUES  (38,'3452','Erick','Giraldo','Puerta Norte No6','agrobiotecnologa','18');
INSERT INTO Estudiante VALUES  (39,'2443','luis','Carmona','noche triste','paramedicos','19');
INSERT INTO Estudiante VALUES  (40,'3452','Enrique','Penagos','ahuehuetes ','tic-si','22');
INSERT INTO Estudiante VALUES  (41,'3498','raul','Arango', 'noche triste No9','administrador','17');
INSERT INTO Estudiante VALUES  (42,'1073','Sandra','Acosta','Hidalgo No12','contabilidad','20');
INSERT INTO Estudiante VALUES  (43,'3792','Maricruz','Medina','Mariano Matamoros SN','Informatica','19');
INSERT INTO Estudiante VALUES  (44,'1073','Gabriel','Martinez','Cuauhtemoc','administracion','23');
INSERT INTO Estudiante VALUES  (45,'2443','Marisol','Cano','Los pinos No15','tic-si','20');

    """
)
conn.commit()

In [17]:
# Creación de la tabla LibAut
conn.executescript(
    """
CREATE TABLE LibAut
 (
 Id_Autor INT,
 Id_Libro INT,
 FOREIGN KEY (Id_Autor) REFERENCES Autor (Id_Autor),
 FOREIGN KEY (Id_Libro) REFERENCES Libro (Id_Libro)
 ); 

INSERT INTO LibAut VALUES(16,1);
INSERT INTO LibAut VALUES (17,2);
INSERT INTO LibAut VALUES (18,3);
INSERT INTO LibAut VALUES(19,4);
INSERT INTO LibAut VALUES(20,5);
INSERT INTO LibAut VALUES(21,6);
INSERT INTO LibAut VALUES(22,7);
INSERT INTO LibAut VALUES(23,8);
INSERT INTO LibAut VALUES(24,9);
INSERT INTO LibAut VALUES(25,10);
INSERT INTO LibAut VALUES(26,11);
INSERT INTO LibAut VALUES(27,12);
INSERT INTO LibAut VALUES(28,13);
INSERT INTO LibAut VALUES(29,14);
INSERT INTO LibAut VALUES(30,15);
INSERT INTO LibAut VALUES(31,16);
INSERT INTO LibAut VALUES(31,17);
INSERT INTO LibAut VALUES(19,18);
INSERT INTO LibAut VALUES(19,19);
    """
)
conn.commit()

In [7]:
# Creación de la tabla Prestamo
conn.executescript(
    """
CREATE TABLE Prestamo
(
Id_Lector INT,
Id_Libro INT,
Fecha_Prestamo VARCHAR(10),
Fecha_Devuelto VARCHAR(10),
Devuelto VARCHAR(10),
FOREIGN KEY (Id_Lector) REFERENCES Estudiante (Id_Lector),
FOREIGN KEY (Id_Libro) REFERENCES Libro (Id_Libro)
);

INSERT INTO Prestamo VALUES (31,1,'08/04/2012','10/04/2012','11/04/2012');
INSERT INTO Prestamo VALUES (32,5,'08/04/2012','10/04/2012','10/04/2012');
INSERT INTO Prestamo VALUES (33,6,'08/04/2012','10/04/2012','12/04/2012');
INSERT INTO Prestamo VALUES (34,5,'07/05/2012','09/05/2012','10/05/2012');
INSERT INTO Prestamo VALUES (35,4,'09/05/2012','11/05/2012','11/05/2012');
INSERT INTO Prestamo VALUES (36,3,'25/05/2012','28/05/2012','28/05/2012');
INSERT INTO Prestamo VALUES (37,1,'12/06/2012','14/06/2012','15/06/2012');
INSERT INTO Prestamo VALUES (38,1,'13/06/2012','15/06/2012','15/06/2012');
INSERT INTO Prestamo VALUES (39,6,'14/01/2013','16/01/2013','16/01/2013');
INSERT INTO Prestamo VALUES (40,7,'16/02/2013','18/02/2013','18/02/2013');
INSERT INTO Prestamo VALUES (41,8,'20/02/2013','22/02/2013','25/02/2013');
INSERT INTO Prestamo VALUES (42,7,'11/03/2013','13/03/2013','13/03/2013');
INSERT INTO Prestamo VALUES (43,10,'27/03/2013','29/03/2013','01/04/2013');
INSERT INTO Prestamo VALUES (44,6,'08/04/2013','10/04/2013','10/04/2013');
INSERT INTO Prestamo VALUES (45,2,'08/04/2013','10/04/2013','10/04/2013');

    """
)
conn.commit()

1. Visualizar la tabla Libro

In [8]:
cur.execute("SELECT * FROM Libro").fetchall()
# Id_Libro | Titulo | Editoria | Area|

[(1, 'El Señor de las Moscas', 'Marruecos', 'Novela'),
 (2, 'El Esclavo', 'Porrua', 'Narracion'),
 (3, 'El Señor de los Anillos', 'FCE', 'Internet'),
 (4, 'Don Quijote de la Mancha', 'Grijalva', 'Narracion'),
 (5, 'visual Estudio Net', 'Alfay Omega', 'informatica'),
 (6, 'Base de Datos', 'Alfay Omega', 'informatica'),
 (7, 'Ingenieria de Software', 'Alfay Omega', 'informatica'),
 (8, 'Un Mexicano Mas', 'planeta', 'novela'),
 (9, 'Entregame tu corazon', 'Marruecos', 'Novela'),
 (10, 'Harry Potter', 'edicciones prado', 'Internet'),
 (11,
  'Harry Potter:Las Reliquias de la Muerte ',
  'edicciones prado',
  'Internet'),
 (12, 'Orgullo y Prejuicio', 'Marruecos', 'Novela'),
 (13, 'Romeo y Julienta', 'Marruecos', 'Novela'),
 (14, 'Navidad en las Montañas', 'Marruecos', 'Narracion'),
 (15, 'El Señor de los Anillos: Las Dos Torres', 'FCE', 'Internet')]

2. Listar los datos de los autores que tengan más de un libro publicado

In [25]:
cur.execute(" \
  SELECT Autor.* \
  FROM Autor LEFT JOIN LibAut                                 \
  ON Autor.Id_Autor = LibAut.Id_Autor \
 GROUP BY Autor.Id_Autor HAVING COUNT(Autor.Id_Autor) > 1").fetchall()

[(19, 'Mario Benedetti', 'USA'), (31, 'Jane Austen', 'Inglesa')]

3.Listar nombre y edad de los estudiantes

In [27]:
cur.execute(" \
  SELECT Nombre, Edad \
  FROM Estudiante").fetchall()

[('Maria', '17'),
 ('Jonathan', '17'),
 ('roberto', '20'),
 ('Paola', '18'),
 ('mayra', '22'),
 ('ivan', '19'),
 ('Alexander', '18'),
 ('Erick', '18'),
 ('luis', '19'),
 ('Enrique', '22'),
 ('raul', '17'),
 ('Sandra', '20'),
 ('Maricruz', '19'),
 ('Gabriel', '23'),
 ('Marisol', '20')]

4. ¿Qué estudiantes pertenecen a la carrera de Informática?

In [31]:
cur.execute(" \
  SELECT Nombre \
  FROM Estudiante\
  WHERE Carrera = 'Informatica'").fetchall()

[('Maricruz',)]

5.Listar los nombres de los estudiantes cuyo apellido comience con la letra G?

In [40]:
cur.execute(" \
  SELECT Nombre \
  FROM Estudiante\
  WHERE Apellido LIKE 'G%'").fetchall()

[('Jonathan',), ('Erick',)]

6.¿Quiénes son los autores del libro “visual Estudio Net”, listar solamente los nombres?

In [42]:
cur.execute(" \
  SELECT C.Nombre \
  FROM Libro A LEFT JOIN LibAut B  \
  ON A.Id_Libro = B.Id_Libro\
  LEFT JOIN Autor C \
  ON B.Id_Autor = C.Id_Autor\
  WHERE A.Titulo = 'visual Estudio Net'").fetchall()

[('Altamirano',)]

7.¿Qué autores son de nacionalidad USA o Francia?

In [47]:
cur.execute(" \
  SELECT Nombre \
  FROM Autor\
  WHERE Nacionalidad in ('Francia','USA')").fetchall()

[('Barbara Gostmich',), ('Mario Benedetti',), ('Og Mandino',)]

8.¿Qué libros No Son del Área de Internet?

In [48]:
cur.execute(" \
  SELECT Titulo \
  FROM Libro\
  WHERE Area is not 'internet'").fetchall()

[('El Señor de las Moscas',),
 ('El Esclavo',),
 ('El Señor de los Anillos',),
 ('Don Quijote de la Mancha',),
 ('visual Estudio Net',),
 ('Base de Datos',),
 ('Ingenieria de Software',),
 ('Un Mexicano Mas',),
 ('Entregame tu corazon',),
 ('Harry Potter',),
 ('Harry Potter:Las Reliquias de la Muerte ',),
 ('Orgullo y Prejuicio',),
 ('Romeo y Julienta',),
 ('Navidad en las Montañas',),
 ('El Señor de los Anillos: Las Dos Torres',),
 ('Emma',),
 ('Sensatez y sensibilidad',),
 ('La Muerte',),
 ('La Tregua',)]

9. ¿Qué libros se prestó el Lector “Marisol Cano”?

In [51]:
cur.execute(" \
  SELECT A.Titulo \
  FROM Libro A LEFT JOIN Prestamo B  \
  ON A.Id_Libro = B.Id_Libro\
  LEFT JOIN Estudiante C \
  ON B.Id_Lector = C.Id_Lector\
  WHERE C.Nombre = 'Marisol'").fetchall()

[('El Esclavo',)]

10. Listar el nombre del estudiante de menor edad

In [53]:
cur.execute(" \
  SELECT Nombre \
  FROM Estudiante \
  WHERE Edad = (SELECT MIN(Edad) FROM Estudiante)").fetchall()

[('Maria',), ('Jonathan',), ('raul',)]

11. Listar los nombres de los estudiantes que se prestaron Libros de Base de Datos

In [55]:
cur.execute(" \
  SELECT C.Nombre \
  FROM Estudiante C LEFT JOIN Prestamo B  \
  ON C.Id_Lector = B.Id_Lector\
  LEFT JOIN Libro A \
  ON A.Id_Libro = B.Id_Libro\
  WHERE A.Area = 'Base de Datos'").fetchall()

[]

12.Listar los libros de editorial Alfa y Omega

In [57]:
cur.execute(" \
  SELECT Titulo \
  FROM Libro\
  WHERE Editorial = 'Alfay Omega'").fetchall()

[('visual Estudio Net',), ('Base de Datos',), ('Ingenieria de Software',)]

13.Listar los libros que pertenecen al autor Mario Benedetti

In [58]:
cur.execute(" \
  SELECT A.Titulo \
  FROM Libro A LEFT JOIN LibAut B  \
  ON A.Id_Libro = B.Id_Libro\
  LEFT JOIN Autor C \
  ON B.Id_Autor = C.Id_Autor\
  WHERE C.Nombre = 'Mario Benedetti'").fetchall()

[('Don Quijote de la Mancha',), ('La Muerte',), ('La Tregua',)]

14.Listar los títulos de los libros que debían devolverse el 10/04/2012

In [60]:
cur.execute(" \
  SELECT A.Titulo \
  FROM Libro A LEFT JOIN Prestamo B  \
  ON A.Id_Libro = B.Id_Libro\
  WHERE B.Fecha_Devuelto = '10/04/2012'").fetchall()

[('El Señor de las Moscas',), ('visual Estudio Net',), ('Base de Datos',)]

15. Hallar la suma de las edades de los estudiantes

In [62]:
cur.execute(" \
  SELECT SUM(Edad) \
  FROM Estudiante \
  AS Suma_Edades").fetchall()

[(289,)]

16. Listar los datos de los estudiantes cuya edad es mayor al promedio

In [63]:
cur.execute(" \
  SELECT * \
  FROM Estudiante \
  WHERE Edad > (SELECT AVG(Edad) FROM Estudiante )").fetchall()

[(33,
  '6295',
  'roberto',
  'Duque',
  'flor de azalia SN',
  'agrobiotecnologia',
  '20'),
 (35, '3792', 'mayra', 'Aguirre', 'Allende No 3', 'alimentos', '22'),
 (40, '3452', 'Enrique', 'Penagos', 'ahuehuetes ', 'tic-si', '22'),
 (42, '1073', 'Sandra', 'Acosta', 'Hidalgo No12', 'contabilidad', '20'),
 (44, '1073', 'Gabriel', 'Martinez', 'Cuauhtemoc', 'administracion', '23'),
 (45, '2443', 'Marisol', 'Cano', 'Los pinos No15', 'tic-si', '20')]

17.Crear un Procedimiento Almacenado que muestre los libros de un determinado Autor que se especifique.

In [ ]:
CREATE PROCEDURE libros_autor
  @autor varchar(30)
 as
  select titulo
   from libros
   where autor= @autor;

   exec libros_autor_ 'Jane Austen'

18. Crear un Procedimiento Almacenado que inserte nuevos Estudiantes

In [ ]:
CREATE PROCEDURE SPIestudiante
@id_lector INT,
@ci VARCHAR(9),
@nombre VARCHAR(100),
@apellido VARCHAR(100),
@direccion VARCHAR(100),
@carrera VARCHAR(100),
@edad VARCHAR(9)
AS
BEGIN
    INSERT INTO Estudiante (Id_Lector, CI, Nombre, Apellido, Direccion, Carrera, Edad)
                VALUES(@id_lector, @ci, @nombre, @apellido, @direccion, @carrera, @edad)
END

19. Crear un Procedimiento Almacenado que actualice cualquier Libro especificando su código.

In [ ]:
CREATE PROCEDURE SPIlibros
@id_libro INT
@titulo VARCHAR(100),
@editorial VARCHAR(100),
@area VARCHAR(100),

AS
BEGIN
UPDATE Libro 
    SET Titulo = @titulo,
        Editorial = @editorial,
        Area = @area
  WHERE Id_Libro = @id_libro
END

20.Crear un disparador DML que permita listar los registros de la Tabla Estudiantes luego de insertar un nuevo
registro

In [ ]:
create trigger Estudiantes_Sort 
before INSERT 
on 
Estudiante
UPDATE Estudiante

21. Crear una Función (que devuelva una Tabla) que liste los préstamos solicitados por un determinado alumno.

In [ ]:
CREATE FUNCTION Prestamos (
    @Nombre VARCHAR(100)
)
RETURNS TABLE
AS
RETURN
    SELECT B,* \
  FROM Libro A LEFT JOIN LibAut B  \
  ON A.Id_Libro = B.Id_Libro\
  LEFT JOIN Estudiante C \
  ON B.Id_Lector = C.Id_Lector\
  WHERE C.Nombre = @Nombre